module.exports = {
  mode: 'jit',
  purge: {
    enabled: true,
    content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  },
  darkMode: false,
  theme: {
    extend: {
      transitionDuration: {
        0: '0ms',
        50: '50ms',
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
  corePlugins: {
    backdropBlur: false,
    backdropBrightness: false,
    backdropContrast: false,
    backdropFilter: false,
    backdropGrayscale: false,
    backdropHueRotate: false,
    backdropInvert: false,
    backdropOpacity: false,
    backdropSaturate: false,
    backdropSepia: false,
    backgroundBlendMode: false,
    backgroundImage: false,
    blur: false,
    boxDecorationBreak: false,
    brightness: false,
    container: false,
    contrast: false,
    dropShadow: false,
    filter: false,
    gradientColorStops: false,
    grayscale: false,
    hueRotate: false,
    invert: false,
    isolation: false,
    ringOffsetColor: false,
    ringOffsetWidth: false,
    ringOpacity: false,
    ringWidth: false,
    sepia: false,
    saturate: false,
    strokeWidth: false,
  },
};
