module.exports = {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      animation: {
        'loading-before': 'loading-before 1s ease-out infinite',
        'loading-after': 'loading-after 1s ease-out infinite',
      },
      aspectRatio: {
        '4/3': '4 / 3',
        '16/9': '16 / 9',
      },
      keyframes: {
        'loading-before': {
          '0%': {
            left: '-100%',
            width: '100%',
          },
          '100%': {
            left: '100%',
            width: '100%',
          },
        },
        'loading-after': {
          '0%': {
            left: '-100%',
            width: '100%',
          },
          '100%': {
            left: '100%',
            width: '100%',
          },
        },
      },
      transitionDuration: {
        0: '0ms',
        50: '50ms',
      },
    },
    colors: {
      blue: {
        50: 'var(--color--blue50)',
        100: 'var(--color--blue100)',
        200: 'var(--color--blue200)',
        300: 'var(--color--blue300)',
        400: 'var(--color--blue400)',
        500: 'var(--color--blue500)',
        600: 'var(--color--blue600)',
        700: 'var(--color--blue700)',
        800: 'var(--color--blue800)',
        900: 'var(--color--blue900)',
      },
      gray: {
        50: 'var(--color--gray50)',
        100: 'var(--color--gray100)',
        200: 'var(--color--gray200)',
        300: 'var(--color--gray300)',
        400: 'var(--color--gray400)',
        500: 'var(--color--gray500)',
        600: 'var(--color--gray600)',
        700: 'var(--color--gray700)',
        800: 'var(--color--gray800)',
        900: 'var(--color--gray900)',
      },
      green: {
        50: 'var(--color--green50)',
        100: 'var(--color--green100)',
        200: 'var(--color--green200)',
        300: 'var(--color--green300)',
        400: 'var(--color--green400)',
        500: 'var(--color--green500)',
        600: 'var(--color--green600)',
        700: 'var(--color--green700)',
        800: 'var(--color--green800)',
        900: 'var(--color--green900)',
      },
      orange: {
        50: 'var(--color--orange50)',
        100: 'var(--color--orange100)',
        200: 'var(--color--orange200)',
        300: 'var(--color--orange300)',
        400: 'var(--color--orange400)',
        500: 'var(--color--orange500)',
        600: 'var(--color--orange600)',
      },
      red: {
        50: 'var(--color--red50)',
        100: 'var(--color--red100)',
        200: 'var(--color--red200)',
        300: 'var(--color--red300)',
        400: 'var(--color--red400)',
        500: 'var(--color--red500)',
        600: 'var(--color--red600)',
      },
      yellow: {
        50: 'var(--color--yellow50)',
        100: 'var(--color--yellow100)',
        200: 'var(--color--yellow200)',
        300: 'var(--color--yellow300)',
        400: 'var(--color--yellow400)',
        500: 'var(--color--yellow500)',
        600: 'var(--color--yellow600)',
      },
      transparent: 'var(--color--transparent)',
      white: 'var(--color--white)',
      currentColor: 'var(--color--currentColor)',
      error: 'var(--color--error)',
      info: 'var(--color--info)',
      success: 'var(--color--success)',
    },
  },
  variants: {
    extend: {},
  },
  plugins: [
    require('@tailwindcss/forms')({
      strategy: 'class',
    }),
  ],
  corePlugins: {
    backdropBlur: false,
    backdropBrightness: false,
    backdropContrast: false,
    backdropFilter: false,
    backdropGrayscale: false,
    backdropHueRotate: false,
    backdropInvert: false,
    backdropOpacity: false,
    backdropSaturate: false,
    backdropSepia: false,
    backgroundBlendMode: false,
    backgroundImage: false,
    blur: false,
    boxDecorationBreak: false,
    brightness: false,
    container: false,
    contrast: false,
    dropShadow: false,
    filter: false,
    gradientColorStops: false,
    grayscale: false,
    hueRotate: false,
    invert: false,
    isolation: false,
    ringOffsetColor: false,
    ringOffsetWidth: false,
    ringOpacity: false,
    sepia: false,
    saturate: false,
    strokeWidth: false,
  },
};
